# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: location
    scrape_interval: 5s
    static_configs:
      - targets: ['location:80']

  - job_name: db_conn
    scrape_interval: 5s
    static_configs:
      - targets: ['db_conn:80']